#!/usr/bin/env bash

# handle being called from systemd service
if [ -z "$XDG_RUNTIME_DIR" ] && [ -z "$SWAYSOCK"]; then
	uid=$(id -u $USER)
	export XDG_RUNTIME_DIR="/run/user/"$uid"/"
	export SWAYSOCK=$(find $XDG_RUNTIME_DIR -maxdepth 1 -iname 'sway*sock')
fi

grim /home/$USER/Bilder/lockscreen.png
convert -blur 0x6 /home/$USER/Bilder/lockscreen.png /home/$USER/Bilder/lockscreen.png

swaylock -i /home/$USER/Bilder/lockscreen.png
