#!/bin/bash

line=`ag --nobreak --nonumbers --noheading --nocolor "\[Desktop Entry\][^\[]+Name=.+" /usr/share/applications | grep "Name=" | sed -En "s/Name=//p" | /home/linuxbrew/.linuxbrew/bin/fzf --delimiter=":" --with-nth=2 --print-query`; if [ $(echo "$line" | wc -l) -eq 2 ]; then echo "$line" | sed -n 2p | cut -d":" -f1 | xargs basename -s .desktop -a | xargs -r swaymsg -t command exec gtk-launch; else echo -n "$line" | xargs -r swaymsg -t command exec; fi

