#!/bin/bash
desktopEntries=`ag --nobreak --nonumbers --noheading --nocolor "\[Desktop Entry\]((?<!^Name=)[\s\S](?!^\[[^\]]+\]$))*\nName=.*" /usr/share/applications/* $HOME/.local/share/applications /var/lib/snapd/desktop/applications | grep ":Name=" | sed -En "s/Name=//p"`
line=`echo "$desktopEntries" | /home/linuxbrew/.linuxbrew/bin/fzf --delimiter=":" --with-nth=2 --print-query`

if [ $(echo "$line" | wc -l) -eq 2 ]; then 
	program=`echo "$line" | sed -n 2p | cut -d":" -f1`
	swaymsg -t command exec "dex $program"
else
  program=`echo -n $line`
	swaymsg -t command exec "$program"
fi
